# Site settings
title: Dominion League
email: dominionleague@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Dominion League is a free online tournament for competitive Dominion.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# permalink: pretty
plugins:
  - jekyll-paginate

# paginate: 4
# paginate_path: "blog/page:num"
